website:
  title: "Guilherme Maricato"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: outreach.qmd
        text: Outreach
      - href: attachments/cv.pdf # Salve seu PDF com nome simples na pasta raiz
        text: CV