project:
  type: website
  output-dir: docs

website:
  title: "Guilherme Maricato"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: outreach.qmd
        text: Outreach
      - href: attachments/cv.pdf
        text: CV
    right:
      - icon: github
        href: https://github.com/guimaricato
      - icon: linkedin
        href: https://www.linkedin.com/in/guilherme.maricato

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true